import duckdb

"""
# SCHEMA

## ENTITY_TYPES
- ENTITY_TYPE_ID VARCHAR PRIMARY KEY
- ENTITY_TYPE_NAME VARCHAR
- INDEX ON (ENTITY_TYPE_NAME)

## ENTITIES
- ENTITY_ID VARCHAR PRIMARY KEY
- ENTITY_NAME VARCHAR
- NDJSON VARCHAR
- ENTITY_TYPE_ID VARCHAR REFERENCES ENTITY_TYPES(ENTITY_TYPE_ID)
- INDEX ON (ENTITY_NAME)

## SOURCES
- SOURCE_ID VARCHAR PRIMARY KEY
- SOURCE_NAME VARCHAR
- NDJSON VARCHAR
- INDEX ON (SOURCE_NAME)

## RELATIONSHIP_TYPES
- RELATIONSHIP_TYPE_ID VARCHAR PRIMARY KEY
- RELATIONSHIP_TYPE_NAME VARCHAR
- INDEX ON (RELATIONSHIP_TYPE_NAME)

## RELATIONSHIPS
- SUBJECT_ENTITY_ID VARCHAR REFERENCES ENTITIES(ENTITY_ID)
- OBJECT_ENTITY_ID VARCHAR REFERENCES ENTITIES(ENTITY_ID)
- RELATIONSHIP_TYPE_ID VARCHAR REFERENCES RELATIONSHIP_TYPES(RELATIONSHIP_TYPE_ID)
- NDJSON VARCHAR
- CONFIDENCE FLOAT
- INDEX ON (CONFIDENCE)
"""
